[package]
name = "sentinelkit-security-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
actix-web.workspace = true
futures-util.workspace = true
sentinelkit-contract = { path = "../sentinelkit-contract" }
