[package]
name = "sentinelkit-context"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
actix-web.workspace = true
chrono.workspace = true
uuid.workspace = true
futures-util.workspace = true
serde.workspace = true
